apiVersion: v1
kind: ConfigMap
metadata:
  name: wanderlust-backend-config
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: wanderlust
data:
  PORT: "5000"
  MONGODB_URI: "mongodb://mongo:27017/wanderlust"
  REDIS_URL: "redis://redis:6379"
