apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: wanderlust
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongo
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
      protocol: TCP
